version: "3"

services:
  db:
    image: mongo:latest
    container_name: musical_comrade_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=admin      
    expose:
      - "27020"
    ports:
      - "27020:27020"
    volumes:
      - musical-comrade-mongo:/data/db      

volumes:
  musical-comrade-mongo: