version: "3"

services:
  db:
    image: postgres:latest
    container_name: musical_comrade_db
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_DB=musical_comrade_db
      - POSTGRES_PASSWORD=admin
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - musical-comrade-db:/var/lib/postgresql/data      

volumes:
  musical-comrade-db: